kind: Deployment
apiVersion: apps/v1

metadata:
  name: nginx-deployment
  namespace: coco-ns
  labels:
    app: nginx

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  
  template:
    metadata:
      name: nginx-pod
      namespace: coco-ns
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
          - containerPort: 80

